# Generated by Django 2.0.5 on 2018-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='column_id',
            field=models.CharField(choices=[('1', 'left'), ('2', 'middle'), ('3', 'right')], default='1', max_length=1),
        ),
    ]
