# Generated by Django 2.0.5 on 2018-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_column_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='column_id',
            field=models.CharField(choices=[('left', 'left'), ('middle', 'middle'), ('right', 'right')], default='left', max_length=6),
        ),
    ]
